AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  smarti-sandbox - Serverless application with multiple Lambda functions for sandbox environment

Globals:
  Function:
    Runtime: python3.13
    Architectures:
      - arm64
    LoggingConfig:
      LogFormat: JSON
    Tracing: Active
    Tags:
      project: smarti-sandbox
      stage: !Ref StageName
    Environment:
      Variables:
        SECRET_NAME: !Ref SecretName

Parameters:
  StageName:
    Type: String
    Default: sandbox
    Description: Nome do Stage do API Gateway (sandbox)

  SecretName:
    Type: String
    Default: smarti-sandbox/secrets/supabase
    Description: Nome do Secret no Secrets Manager para pegar variáveis

Resources:
  SmartiSandboxApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: smarti-sandbox-api
      StageName: !Ref StageName
      TracingEnabled: true
      Auth:
        ApiKeyRequired: true
      MethodSettings:
        - ResourcePath: "/*"
          HttpMethod: "*"
          LoggingLevel: INFO
          DataTraceEnabled: true
          MetricsEnabled: true
      Tags:
        project: smarti-sandbox
        stage: !Ref StageName


  ProcessSupplierUploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: process_supplier_upload/
      Handler: app.lambda_handler
      AutoPublishAlias: !Ref StageName
      Timeout: 180
      MemorySize: 512
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${SecretName}*
      Events:
        ProcessSupplierUpload:
          Type: Api
          Properties:
            RestApiId: !Ref SmartiSandboxApi
            Path: /process-supplier-upload
            Method: post
            Auth:
              ApiKeyRequired: true

  ProcessPoUploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: process_po_upload/
      Handler: app.lambda_handler
      AutoPublishAlias: !Ref StageName
      Timeout: 180
      MemorySize: 512
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${SecretName}*
      Events:
        ProcessPoUpload:
          Type: Api
          Properties:
            RestApiId: !Ref SmartiSandboxApi
            Path: /process-po-upload
            Method: post
            Auth:
              ApiKeyRequired: true

  ProcessPoFilesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: process_po_files/
      Handler: app.lambda_handler
      AutoPublishAlias: !Ref StageName
      Timeout: 180
      MemorySize: 512
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${SecretName}*
      Events:
        ProcessPoFiles:
          Type: Api
          Properties:
            RestApiId: !Ref SmartiSandboxApi
            Path: /process-po-files
            Method: post
            Auth:
              ApiKeyRequired: true

  ProcessPoMigoMiroUploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: process_po_migo_miro_upload/
      Handler: app.lambda_handler
      AutoPublishAlias: !Ref StageName
      Timeout: 180
      MemorySize: 512
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${SecretName}*
      Events:
        ProcessPoMigoMiroUpload:
          Type: Api
          Properties:
            RestApiId: !Ref SmartiSandboxApi
            Path: /process-po-migo-miro-upload
            Method: post
            Auth:
              ApiKeyRequired: true

  ProcessExportFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: process_export/
      Handler: app.lambda_handler
      AutoPublishAlias: !Ref StageName
      Timeout: 180
      MemorySize: 512
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${SecretName}*
      Events:
        ProcessExport:
          Type: Api
          Properties:
            RestApiId: !Ref SmartiSandboxApi
            Path: /process-export
            Method: post
            Auth:
              ApiKeyRequired: true

  ProcessOrderDetailsExportFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: process_order_details_export/
      Handler: app.lambda_handler
      AutoPublishAlias: !Ref StageName
      Timeout: 180
      MemorySize: 512
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${SecretName}*
      Events:
        ProcessOrderDetailsExport:
          Type: Api
          Properties:
            RestApiId: !Ref SmartiSandboxApi
            Path: /process-order-details-export
            Method: post
            Auth:
              ApiKeyRequired: true

Outputs:
  ProcessSupplierUploadApi:
    Description: API Gateway endpoint URL for Process Supplier Upload
    Value: !Sub "https://${SmartiSandboxApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/process-supplier-upload"
  ProcessSupplierUploadFunction:
    Description: Lambda Function ARN
    Value: !GetAtt ProcessSupplierUploadFunction.Arn
  ProcessSupplierUploadFunctionIamRole:
    Description: Implicit IAM Role created for the function
    Value: !GetAtt ProcessSupplierUploadFunctionRole.Arn

  ProcessPoUploadApi:
    Description: API Gateway endpoint URL for Process PO Upload
    Value: !Sub "https://${SmartiSandboxApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/process-po-upload"
  ProcessPoUploadFunction:
    Description: Lambda Function ARN
    Value: !GetAtt ProcessPoUploadFunction.Arn
  ProcessPoUploadFunctionIamRole:
    Description: Implicit IAM Role created for the function
    Value: !GetAtt ProcessPoUploadFunctionRole.Arn

  ProcessPoFilesApi:
    Description: API Gateway endpoint URL for Process PO Files
    Value: !Sub "https://${SmartiSandboxApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/process-po-files"
  ProcessPoFilesFunction:
    Description: Lambda Function ARN
    Value: !GetAtt ProcessPoFilesFunction.Arn
  ProcessPoFilesFunctionIamRole:
    Description: Implicit IAM Role created for the function
    Value: !GetAtt ProcessPoFilesFunctionRole.Arn

  ProcessPoMigoMiroUploadApi:
    Description: API Gateway endpoint URL for Process PO Migo Miro Upload
    Value: !Sub "https://${SmartiSandboxApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/process-po-migo-miro-upload"
  ProcessPoMigoMiroUploadFunction:
    Description: Lambda Function ARN
    Value: !GetAtt ProcessPoMigoMiroUploadFunction.Arn
  ProcessPoMigoMiroUploadFunctionIamRole:
    Description: Implicit IAM Role created for the function
    Value: !GetAtt ProcessPoMigoMiroUploadFunctionRole.Arn

  ProcessExportApi:
    Description: API Gateway endpoint URL for Process Export
    Value: !Sub "https://${SmartiSandboxApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/process-export"
  ProcessExportFunction:
    Description: Lambda Function ARN
    Value: !GetAtt ProcessExportFunction.Arn
  ProcessExportFunctionIamRole:
    Description: Implicit IAM Role created for the function
    Value: !GetAtt ProcessExportFunctionRole.Arn

  ProcessOrderDetailsExportApi:
    Description: API Gateway endpoint URL for Process Order Details Export
    Value: !Sub "https://${SmartiSandboxApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/process-order-details-export"
  ProcessOrderDetailsExportFunction:
    Description: Lambda Function ARN
    Value: !GetAtt ProcessOrderDetailsExportFunction.Arn
  ProcessOrderDetailsExportFunctionIamRole:
    Description: Implicit IAM Role created for the function
    Value: !GetAtt ProcessOrderDetailsExportFunctionRole.Arn